set magic " set magic on

set title " set title

set nocompatible " vim, not vi

set autoindent " always set autoindenting on

set smartindent " add indentation itens in vim's edited files

set shiftwidth=4 " use 4 spacs for each tab (with autoindenting)

set expandtab " indent with spaces

" force tabs to be displayed to 4 spaces
set tabstop=4
set softtabstop=4

" display tabs and trailing spaces
set list
set listchars=tab:\ →,trail:·,nbsp:_

" allow backspacing over everything in insert mode
set backspace=indent,eol,start " backspacing over everything in insert mode

set history=50 " 50 lines of commandline history

set undolevels=50 " 50 undo actions

set incsearch " incremental searching

set hlsearch " hilight searches

set ignorecase " ignore case of searches

set smartcase " just without search pattern

" backup in the right place
set nowritebackup
set nobackup
set noswapfile
set backupdir=/tmp

set hidden " don't write buffers to disk when put then to background

" always ignore some files extensions
set wildignore=*.bak,*.o,*.e,*~,*.obj,*.swp,.git,*.rbc,*.class,.svn,vendor/gems/*,#*#

set showcmd " display incomplete commands

set showmatch " show the matching bracket

set textwidth=78 " number of characters by line

set nomodeline " secure option

" no bell sounds
set visualbell
set noerrorbells " (for errors)

" if terminal support syntax hilight, turn it on
if &t_Co > 1
	syntax enable
	syntax on
endif

" set colors for dark background
set background=dark

" highlight current line
set cursorline

" show the cursor position
set ruler

" more informative statusbar
set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [POS=%04l,%04v][%p%%]\ [LEN=%L]\ [BUFFER:%n]

set laststatus=2 " always show status line

set encoding=utf-8 " charset

" completing words
function! MoshTabOrComplete()
	if col('.')>1 && strpart(getline('.'),col('.')-2,3) =~ '^\w'
		return "\<C-N>"
	else
		return "\<Tab>"
endfunction

inoremap <D-/> <C-R>=MoshTabOrComplete()<CR>

" utf8 conversion
nmap ,utf8 !recode -q ISO-8859-1..utf-8

set number " line numbers

set ttyfast " telling vim you're a billy the kid with keyboards

"set lazyredraw " only redraws screen if necessary

set autoread " watch for file changes

set noautowrite " don't automagically write on :next

autocmd BufWritePre * :%s/\r//e " removing win/dos cr/lf

autocmd BufWritePre * :%s/\s\+$//e " removing trailing spaces

filetype on " enable filetype detection

" loading vundle's configs and settings
source ~/.vim/bundle/bundles.vim

filetype plugin indent on " enable filetype specific plugin/indenting

" if you wish use configuration by languages
" - examples :
" autocmd FileType make setlocal noexpandtab
" autocmd FileType ruby setlocal expandtab ts=2 sts=2 sw=2

" make uses real tabs
autocmd FileType make setlocal noexpandtab

" sets for .rst
autocmd BufNewFile,BufRead *.rst setfiletype rst
autocmd FileType rst setlocal spelllang=pt-BR spell

" sets for .textiles
autocmd BufNewFile,BufRead *.textile setfiletype textile
autocmd FileType textile setlocal nowrap spelllang=pt-BR spell

" sets for .md
autocmd BufNewFile,BufRead *.md setfiletype md
autocmd FileType md setlocal spelllang=pt-BR spell

" treat .json files as .js
autocmd BufNewFile,BufRead *.json setfiletype json syntax=javascript

" Python follow PEP8 (http://www.python.org/dev/peps/pep-0008/)
autocmd FileType python setlocal expandtab softtabstop=4 tabstop=4 shiftwidth=4 textwidth=78

" Java specific stuff
autocmd FileType java setlocal expandtab softtabstop=4 tabstop=4 shiftwidth=4 nowrap
let java_highlight_all=1
let java_highlight_debug=1
let java_ignore_javadoc=1
let java_highlight_functions=1
let java_mark_braces_in_parens_as_errors=1

