" set magic on
set magic

" set title
set title

" vim, not vi
set nocompatible

" always set autoindenting on
set autoindent

" add indentation itens in vim's edited files
set smartindent

" use 4 spaces for each tab (with autoidenting)
set shiftwidth=4

" use tabs instead spaces
set noexpandtab

" force tabs to be displayed to 4 spaces
set tabstop=4
set softtabstop=4

" display tabs and trailing spaces
set list
set listchars=tab:\ →,trail:·,nbsp:_

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

" keep 50 lines of command line history
set history=50

" do incremental searching
set incsearch

" hilight searches by default
set hlsearch

" ignore case of searches
set ignorecase

" backup in the right place
set backupdir=/tmp
set nobackup
set nowb
set noswapfile

" always ignore some files extensions
set wildignore=*.bak,*.o,*.e,*~,*.obj,*.swp,#*#

" display incomplete commands
set showcmd

" show the matching bracket for the last ')'
set showmatch

" setting the number of characters by line
set textwidth=78

" secure option
set nomodeline

" no bell sound (for error)
set noerrorbells

" if terminal support syntax hilight, turn it on
if &t_Co > 1
	syntax enable
endif

" set colors for dark background
set background=dark

" highlight current line
"set cursorline

" show the cursor position
"set ruler

" more informative statusbar
:set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [POS=%04l,%04v][%p%%]\ [LEN=%L]\ [BUFFER:%n]

" always show status line
set laststatus=2

" charset utf-8
set encoding=utf-8

" completing words
function! MoshTabOrComplete()
	if col('.')>1 && strpart(getline('.'),col('.')-2,3) =~ '^\w'
		return "\<C-N>"
	else
		return "\<Tab>"
endfunction

inoremap <D-/> <C-R>=MoshTabOrComplete()<CR>

" utf8 conversion
nmap ,utf8 !recode -q ISO-8859-1..utf-8

" line numbers
set number

" telling vim a billy the kid with keyboards
set ttyfast

" only redraws screen if necessary
set lazyredraw

" watch for file changes
set autoread

" don't automagically write on :next
set noautowrite

" removing win/dos cr/lf
autocmd BufWritePre * :%s/\r//e

" removing trailing spaces from files
autocmd BufWritePre * :%s/\s\+$//e

" enable file type detection
filetype on

" enable filetype-specific indenting
filetype indent on

" enable filetype-specific plugins
filetype plugin on

" set no textwidth for .rst
autocmd BufNewFile,BufRead *.rst setfiletype rst
autocmd FileType rst setlocal tw=8000 spelllang=pt-BR spell

" set no textwidth for .textiles
autocmd BufNewFile,BufRead *.textile setfiletype textile
autocmd FileType textile setlocal tw=8000 spelllang=pt-BR spell

" treat .json files as .js
autocmd BufNewFile,BufRead *.json setfiletype json syntax=javascript

" if you wish use configuration by languages
" autocmd FileType make setlocal noexpandtab
" autocmd FileType ruby setlocal expandtab ts=2 sts=2 sw=2

" Java specific stuff
autocmd FileType java setlocal nowrap
let java_highlight_all=1
let java_highlight_debug=1

let java_ignore_javadoc=1
let java_highlight_functions=1
let java_mark_braces_in_parens_as_errors=1

