[general]
import = [
#"themes/dracula.toml",
"themes/gruvbox-dark.toml",
]

[env]
TERM = "alacritty"

[window]
startup_mode="Maximized"
decorations="None"

[font]
#normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
size=14.0
[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Medium"

[cursor]
style = { shape = "Block", blinking = "Never" }
