export LANG=en_US.UTF-8

# History
# setopt inc_append_history share_history
HISTSIZE=10000000
SAVEHIST=10000000
HISTFILE=$HOME/.cache/zsh/history
setopt appendhistory
export HISTCONTROL=ignoredups
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help"

# grep
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"

# FZF
source <(fzf --zsh)

# Git
export GPG_TTY=$(tty)

git-cleanup-branches() {
    git fetch --prune
    git branch -vv | grep -E '(: gone]|merged)' | grep -vE '(^\*|master|main)' | awk '{print $1}' | xargs -r git branch -D
    git branch -vv | awk '/^[^*]/ && !/\[origin\// {print $1}' | grep -vE '(master|main)' | xargs -r git branch -D
}

# Options (man zshoptions)
stty stop undef
unsetopt beep
setopt autocd
setopt interactive_comments

# Color
autoload -Uz colors && colors

# Aliases
alias e="exit"
alias ls="ls --color=auto"
alias ll="ls -lh"
alias la="ls -a"
alias lla="ls -lah"
alias lsd='ls -lh | grep "^d"'
alias cleanup="find . -type f -name '*DS_Store' -ls -delete"
alias g="git"
alias bua="brew update && brew upgrade && brew cleanup"
alias d="docker"
alias docker-cleanup="docker-compose down && docker container ls -aq | xargs docker container rm -f && docker volume ls -q | xargs docker volume rm -f"
alias docker-clean-restart="docker-cleanup && docker-compose up -d"
alias em="emacs &"
alias p="cd ~/projects"

# Starship
eval "$(starship init zsh)"

# asdf
if [ -f "/opt/homebrew/opt/asdf/bin/asdf" ]; then
    # Add asdf and shims to PATH (before other PATH modifications)
    export ASDF_DIR="/opt/homebrew/opt/asdf"
    export PATH="$HOME/.asdf/shims:$ASDF_DIR/bin:$PATH"

    # Initialize asdf
    eval "$(asdf exec env)"

    # Add completions to fpath
    fpath+=("$(brew --prefix asdf)/share/zsh/site-functions")
    autoload -Uz compinit && compinit

    # GO lang with asdf
    export ASDF_GOLANG_MOD_VERSION_ENABLED=true
    if [ -f "$HOME/.asdf/plugins/golang/set-env.zsh" ]; then
        . "$HOME/.asdf/plugins/golang/set-env.zsh"
    fi

    # JAVA with asdf
    if [ -f "$HOME/.asdf/plugins/java/set-java-home.zsh" ]; then
        . "$HOME/.asdf/plugins/java/set-java-home.zsh"
    fi

    # DOTNET with asdf
    if [ -f "$HOME/.asdf/plugins/dotnet/set-dotnet-env.zsh" ]; then
        . "$HOME/.asdf/plugins/dotnet/set-dotnet-env.zsh"
    fi
fi

# Node js
export PATH="/opt/homebrew/opt/node@20/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/node@20/lib"
export CPPFLAGS="-I/opt/homebrew/opt/node@20/include"
