export LANG=en_US.UTF-8

# History
# setopt inc_append_history share_history
HISTSIZE=10000000
SAVEHIST=10000000
HISTFILE=$HOME/.cache/zsh/history
setopt appendhistory
export HISTCONTROL=ignoredups
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help"

# grep
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"

# FZF
source <(fzf --zsh)

# asdf
. /opt/homebrew/opt/asdf/libexec/asdf.sh

# Node js
export PATH="/opt/homebrew/opt/node@20/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/node@20/lib"
export CPPFLAGS="-I/opt/homebrew/opt/node@20/include"

# Git
export GPG_TTY=$(tty)

# Options (man zshoptions)
stty stop undef
unsetopt beep
setopt autocd
setopt interactive_comments

# Color
autoload -Uz colors && colors

# Aliases
alias e="exit"
alias ls="ls --color=auto"
alias ll="ls -lh"
alias la="ls -a"
alias lla="ls -lah"
alias lsd='ls -lh | grep "^d"'
alias cleanup="find . -type f -name '*DS_Store' -ls -delete"
alias g="git"
alias git-cleanup-local-branches="git branch | grep -v "main" | xargs git branch -D"
alias bua="brew update && brew upgrade && brew cleanup"
alias d="docker"
alias docker="podman"
alias docker-compose="podman-compose"
alias em="emacs &"
alias p="cd ~/projects"

# GO lang with asdf
export ASDF_GOLANG_MOD_VERSION_ENABLED=true
. ~/.asdf/plugins/golang/set-env.zsh

#JAVA_HOME with asdf
. ~/.asdf/plugins/java/set-java-home.zsh
