# GO lang
export PATH=$PATH:$(go env GOPATH)/bin
export PATH=$PATH:$(go env GOROOT)/bin

# Nods js
export PATH="/opt/homebrew/opt/node@20/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/node@20/lib"
export CPPFLAGS="-I/opt/homebrew/opt/node@20/include"

# History
HISTSIZE=10000000
SAVEHIST=10000000
HISTFILE=$HOME/.cache/zsh/history
setopt appendhistory
export HISTCONTROL=ignoredups
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help"

# Options (man zshoptions)
stty stop undef
unsetopt beep
setopt autocd
setopt interactive_comments

# Color
autoload -Uz colors && colors

# Aliases
alias e="exit"
alias ls="ls --color=auto"
alias ll="ls -lh"
alias la="ls -a"
alias lla="ls -lah"
alias lsd='ls -lh | grep "^d"'
alias g="git"
alias em="emacs &"
alias p="cd ~/projects"
alias git-cleanup-local-branches="git branch | grep -v "main" | xargs git branch -D"
# alias docker="podman"
# alias docker-compose="podman-compose"

#JAVA_HOME with asdf
. ~/.asdf/plugins/java/set-java-home.zsh
