#!/bin/bash

# ask for the administrator password upfront
sudo -v

# update existing 'sudo' time stamp until 'instalation' is finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# set computer name (as done via System Preferences > Sharing)
echo "Setting this machine name : valholl..."
sudo scutil --set ComputerName "valholl"
sudo scutil --set HostName "valholl"
sudo scutil --set LocalHostName "valholl"
sudo defaults write /Libary/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "valholl"

# save to disk (not to iCloud) by default
echo "Setting to save to disk (not to iCloud) by default"
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

# automatically quit printer app once the print jobs complete
echo "Setting to automatically quit printer app once the print jobs complete..."
defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

# check for software update daily, not just once per week
echo "Setting to check for software update daily..."
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

# finder: show all filename extensions
echo "Setting finder to show all filename extensions..."
defaults write com.apple.finder AppleShowAllExtensions -bool true

# finder: show status bar
echo "Setting finder to show status bar..."
defaults write com.apple.finder ShowStatusBar -bool true

# when performing a search, search the current folder by default
echo "Setting finder to search the current folde by default..."
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

# avoid creating .DS_Store files on network volumes,
# don't work with external usb drivers
echo "Avoiding creating .DS_Store files on network volumes..."
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# empty trash securely by defult
echo "Setting to empty trash securely by default..."
defaults write com.apple.finder EmptyTrashSecurely -bool true

# show the ~/Library folder
echo "Setting to show ~/Library folder..."
chflags nohidden ~/Library

# stop pasting full names when copying an email address in mac osx mail
echo "Stopping pasting full names in mac osx mail..."
defaults write com.apple.mail AddressesIncludeNameOnPasteboard -bool false

# only use utf-8 in Terminal.app
echo "Using only UTF-8 in Terminall.app..."
defaults write com.apple.terminal StringEncodings -array 4

# no more Time Machine prompting to use new hard drives as backup volumes
echo "No more Time Machine prompting to use new HDs as backup volumes..."
defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

# disable local time machine backups
echo "To turn off local time machine backups...run:"
echo "  $hash tmutil &> /dev/null && sudo tmutil disablelocal"
# hash tmutil &> /dev/null && sudo tmutil disablelocal
echo "And enter with your password."
#echo "Complete."

# use plain text mode for new TextEdit documents
echo "Making TextEdit better..."
defaults write com.apple.TextEdit RichText -int 0
# open and save files as UTF-8 in TextEdit
defaults write com.apple.TextEdit PlainTextEncoding -int 4
defaults write com.apple.TextEdit PlainTextEncodingForWrite -int 4

