# PATH
export PATH="$HOME/.local/bin:/usr/local/bin":$PATH

# Defaults
export TERM="st-256color"
export TERMINAL="st"
export ALTERNATE_EDITOR="vim"
export EDITOR="vim"
export VISUAL="emacsclient -c"

# History
HISTSIZE=10000000
SAVEHIST=10000000
HISTFILE=$HOME/.cache/zsh/history
setopt appendhistory
export HISTCONTROL=ignoredups
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help"

# Options (man zshoptions)
stty stop undef
unsetopt beep
setopt autocd
setopt interactive_comments

# Color
autoload -Uz colors && colors

# Functions
function source_if_exists() {
    [ -f "$ZDOTDIR/$1" ] && source "$ZDOTDIR/$1"
}

function zsh_add_plugin() {
    MAINTENER_NAME=$(echo $1 | cut -d "/" -f 1)
    PLUGIN_NAME=$(echo $1 | cut -d "/" -f 2)
    if [ -d "$ZDOTDIR/plugins/$MAINTENER_NAME/$PLUGIN_NAME" ]; then
        source_if_exists "plugins/$MAINTENER_NAME/$PLUGIN_NAME/$PLUGIN_NAME.plugin.zsh" || \
        source_if_exists "plugins/$MAINTENER_NAME/$PLUGIN_NAME/$PLUGIN_NAME.zsh" || \
        source_if_exists "plugins/$MAINTENER_NAME/$PLUGIN_NAME/$PLUGIN_NAME.sh"
    else
        git clone "https://github.com/$1.git" "$ZDOTDIR/plugins/$MAINTENER_NAME/$PLUGIN_NAME" --depth=1;
        zsh_add_plugin $1
    fi
}

# Plugins
# For more plugins: https://github.com/unixorn/awesome-zsh-plugins
# More completions https://github.com/zsh-users/zsh-completions
zsh_add_plugin "zsh-users/zsh-autosuggestions"
#zsh_add_plugin "zdharma-continuum/fast-syntax-highlighting"
zsh_add_plugin "dracula/zsh-syntax-highlighting"
zsh_add_plugin "zsh-users/zsh-syntax-highlighting"
#zsh_add_plugin "dracula/zsh"

# Aliases
alias e="exit"
alias ls="ls --color=auto"
alias ll="ls -lh"
alias la="ls -a"
alias lla="ls -lah"
alias lsd='ls -lh | grep "^d"'
alias g="git"
alias em="emacsclient -c"
alias p="cd ~/projects"
#alias emacs-daemon-enable="systemctl --user enable --now emacs"
#alias emacs-daemon-disable="systemctl --user disable --now emacs"
#alias emacs-daemon-stop="systemctl --user stop --now emacs"
#alias emacs-daemon-restart="systemctl --user restart --now emacs"
alias cpu-temperature="echo $(($(cat /sys/class/thermal/thermal_zone0/temp) / 1000))C"
alias gpu-temperature="echo $(nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader,nounits)C"

# asdf
. /opt/asdf-vm/asdf.sh

# JAVA_HOME with asdf
. ~/.asdf/plugins/java/set-java-home.zsh
