nvidia-settings --load-config-only & 
xset s off
xset -dpms
xset s noblank
xset r rate 210 40
xset m 5 2 & 
setxkbmap -model abnt -layout us -variant intl
setxkbmap -option ctrl:nocaps
xrandr --setprovideroutputsource modesetting NVIDIA-0 
xrandr --auto 
#xrandr -s 1280x800
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

while true
do
    TEMP="$(($(cat /sys/class/thermal/thermal_zone0/temp) / 1000))C"
    GPUTEMP="$(nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader,nounits)C"
    LOCALTIME="$(date '+%d/%m/%y - %R')"
    xsetroot -name "$TEMP $GPUTEMP $LOCALTIME"
    sleep 30s
done &

exec dwm
